name = "SimpleWeightedGraphs"
uuid = "47aef6b3-ad0c-573a-a1e2-d07658019622"
authors = ["JuliaGraphs contributors"]
version = "1.5.1"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Graphs = "1.7"
LinearAlgebra = "1.6"
Markdown = "1.6"
SparseArrays = "1.6"
julia = "1.6"
